### ISSUE TITLE
Remove unnecessary files, note coloring

### ISSUE THREAD

**Issue by 1033Forest** [skyli91/simply-love-noteskin#2]
All those "burger" and "key" and "para whatever" notes can be removed, since this only works on techno. And edit the lua file, to remove all these notes that aren't needed. Same thing with the "hand whatever" and "leftfist", "leftfoot", etc. Remove everything except left/right, up/down, the diagonals, and center. It would look weird to use this noteskin on other gametypes.
And for the center, can it be pink/purple like the original technomotion game? I can use paint.net to re-hue it. A center receptor still needs to be worked on.

I'd like to see a rhythm colored version of this, with blue holds/gray rolls (5.0) and note colored holds/rolls (5.1). I will re-hue the images according to this:
4th - Blue
8th - Red
12th - Pink
16th - Yellow
24th - Purple
32nd - Teal
48th - Orange
64th - Green
192nd - Gray

**Comment by 1033Forest** [comment]
I am trying to re-hue them but it's not giving me the colors I want. The colors I want to use are:
http://i.imgur.com/dsL15SN.png

I need help creating images for them. In 5.0, the holds would be blue and the rolls gray. 5.1, holds and rolls note colored. The 192nd color could be the same as the gray roll notes in the original 3.95 version of the noteskin.

And the color for "12th" could be the new center panel color (the center on techno pads is pink).

http://i.imgur.com/4RyjCEF.jpg New arrow explosion graphic (got this from the PIU Pro noteskin). To get the rotations right here they are:
DownLeft: 0
Left: 45
UpLeft: 90
Down: 315
Up: 135
UpRight: 180
Right: 225
DownRight: 270

And for the center explosion, rotate it 45 so it looks like a diamond.

**Comment by s-k-y-l-i** [comment]
Hi! Thanks for the response! 

I think, the techno gamemode doesn't have a center button, at least in stepmania. Only pump it up has it that's why it is yellow, but I'll make a child noteskin with pink center.

I like the colors on that pic and the rhythm coloring is a good idea too. Is it also possible to make it random to rhythm?  I really don't know anything with lua but I'm not bad at Photoshop :)  so I'll make a color changed version and I'd also want to make a version for couples play. And maybe one without the white border from thethe image you linked(but that would have no animation as I can't make it).

And nice find on the explosions! Thank you :) and what should be the bright explosion(or dim)? 

Is it a good idea to make player 2 purple to yellow?

**Comment by 1033Forest** [comment]
I prefer P1 blue and P2 red, and in case routines with more players get supported, P3 yellow and P4 green.

Techno mode does have a center button. There's techno-single5 and techno-double5 mode (same as pump), which the actual arcade Technomotion also had. And it is actually pink.
http://i.ushipcdn.com/resize.php?path=%2Fstatic%2Fbed903ba-e624-4316-8.jpg&w=270&h=210

The single and double 5 mode can be selected in the default theme, but in Simply Love it only lets you select techno-single8 and double8. It is also possible to make any dance noteskin support techno, as long as it has no holds that correspond to each direction. Put this in the lua file:
After UpRight = "Down", enter and put this:
    DownLeft = "Down",
    DownRight = "Down",
and be sure to put a tab before each line.

Under the rotations, after UpRight = 225, enter and put this:
    DownLeft = 45,
    DownRight = 315,
Also put a tab before each line.

**Comment by s-k-y-l-i** [comment]
Oh I see, I only tried the 8 panel mode. I was thinking about a colorful 2 player mode with rhythm coloring, is that a bad idea with all the colors?  Maybe player 1 warm colors and place 2 cold colors? 
Oh and I was thinking about the new arrows animation and it doesn't look impossible to make :) so when I'm at home and have time, I'll continue working on it :)

**Comment by 1033Forest** [comment]
Maybe, but random coloring is only possible in 5.1 I think. I think it could be like this:
P1's warm colors:
4th - Pink
8th - Red
12th - Orange
16th - Yellow
and the same thing repeats for 24th-64th.

P2 cool colors:
4th - Purple
8th - Blue
12th - Teal
16th - Green
and repeat for 24th-64th

Or, maybe reverse the color order for 24th-64th, to give a more unique color pattern.

**Comment by 1033Forest** [comment]
And a center panel in pink would fit well, since later on, there will be an ability to add custom step types, so I could create a 9 panel game out of this. Maybe use the pop'n game type to create a 9 panel noteskin (though it'd look weird in 5 panel, it's only upleft, down, center, up, and upright...).

Left White = DownLeft
Left Yellow = Left
Left Green = UpLeft
Left Blue = Down
Red = Center
Right Blue = Up
Right Green = UpRight
Right Yellow = Right
Right White = DownRight
(you don't have to use these colors, these are just the button names for pop'n game mode).

I could edit the lua file, instead of redirecting the pop'n notes to "Burger", I could make them redirect to the buttons in this noteskin. So it supports dance, pump, techno, and pop'n. I could make it support KB7 too (the space could be the center button)

Key1 = UpLeft
Key2 = Left
Key3 = DownLeft
Key4 (Space) = Center
Key5 = DownRight
Key6 = Right
Key7 = UpRight

I got this pattern from Jousway's FFRHD 7K (decided to use center instead of down for the space bar key)

I can even make it support para (even though dance/pump/techno noteskins don't look like para arrows): Left, UpLeft, Up, UpRight, Right

EZ2: Use upleft, down, and upright arrows, and centers for the hands

**Comment by 1033Forest** [comment]
For the unused beat color holds and rolls the name of the color at the end of each file name is in Hungarian?

**Comment by s-k-y-l-i** [comment]
yes, those are just my backup images :D i'll rename them when i'll use them :)

**Comment by s-k-y-l-i** [comment]
Issue is done in the "sexy" noteskin
